[package]
name = "cargo-template"
version = "0.1.0"
edition = "2021"
default-run = "cargo-template"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.49"
clap = "3.0.0-beta.5"
